services:
  hugo:
    image: klakegg/hugo:ext-alpine
    command: server --bind 0.0.0.0 --buildDrafts --watch
    volumes:
      - .:/src:Z
    ports:
      - "1313:1313"
    environment:
      - HUGO_BASEURL=http://localhost:1313
      - HUGO_UID=1000
      - HUGO_GID=1000
